"""initial schema: tenancy, workspace, claims, consent, runs

Revision ID: f50422936b34
Revises:
Create Date: 2026-08-03 20:03:49.782003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f50422936b34"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("budget_min", sa.BigInteger(), nullable=False),
        sa.Column("budget_max", sa.BigInteger(), nullable=False),
        sa.Column("last_contact_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 100", name="ck_lead_score_range"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lead_org_score", "leads", ["org_id", "score"], unique=False)
    op.create_index(op.f("ix_leads_org_id"), "leads", ["org_id"], unique=False)
    op.create_table(
        "operators",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email", name="uq_operator_org_email"),
    )
    op.create_index(op.f("ix_operators_org_id"), "operators", ["org_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("operator_id", sa.String(length=64), nullable=True),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("messages_json", sa.Text(), nullable=True),
        sa.Column("deferred_json", sa.Text(), nullable=True),
        sa.Column("pending_approvals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_org_created", "runs", ["org_id", "created_at"], unique=False)
    op.create_index(op.f("ix_runs_org_id"), "runs", ["org_id"], unique=False)
    op.create_index(op.f("ix_runs_session_id"), "runs", ["session_id"], unique=False)
    op.create_table(
        "suggestions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("impact", sa.String(length=16), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suggestions_org_id"), "suggestions", ["org_id"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("lead_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendar_events_org_id"), "calendar_events", ["org_id"], unique=False)
    op.create_index("ix_event_org_starts", "calendar_events", ["org_id", "starts_at"], unique=False)
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("lead_id", sa.String(length=64), nullable=False),
        sa.Column("predicate", sa.String(length=100), nullable=False),
        sa.Column("object_value", sa.Text(), nullable=False),
        sa.Column("object_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.String(length=32), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("asserted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decay_policy", sa.String(length=16), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=64), nullable=True),
        sa.Column("superseded_by", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('normal', 'sensitive', 'protected')", name="ck_claim_sensitivity"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'contradicted', 'retracted', 'tombstoned')",
            name="ck_claim_status",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_claim_confidence"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_claim_lead_predicate", "claims", ["lead_id", "predicate"], unique=False)
    op.create_index("ix_claim_org_status", "claims", ["org_id", "status"], unique=False)
    op.create_index(op.f("ix_claims_lead_id"), "claims", ["lead_id"], unique=False)
    op.create_index(op.f("ix_claims_org_id"), "claims", ["org_id"], unique=False)
    op.create_table(
        "consents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("lead_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("basis", sa.String(length=32), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('granted', 'revoked', 'expired', 'never_asked')", name="ck_consent_status"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id", "channel", name="uq_consent_lead_channel"),
    )
    op.create_index(op.f("ix_consents_lead_id"), "consents", ["lead_id"], unique=False)
    op.create_index(op.f("ix_consents_org_id"), "consents", ["org_id"], unique=False)
    op.create_table(
        "email_threads",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("sender", sa.String(length=200), nullable=False),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unread", sa.Boolean(), nullable=False),
        sa.Column("needs_response", sa.Boolean(), nullable=False),
        sa.Column("lead_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_org_received", "email_threads", ["org_id", "received_at"], unique=False
    )
    op.create_index(op.f("ix_email_threads_org_id"), "email_threads", ["org_id"], unique=False)
    op.create_table(
        "run_tool_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("tool_call_id", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('proposed', 'executed', 'denied', 'failed')", name="ck_tool_call_status"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "tool_call_id", name="uq_tool_call_run_id"),
    )
    op.create_index(op.f("ix_run_tool_calls_run_id"), "run_tool_calls", ["run_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lead_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_task_org_due", "tasks", ["org_id", "due_at"], unique=False)
    op.create_index(op.f("ix_tasks_org_id"), "tasks", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_org_id"), table_name="tasks")
    op.drop_index("ix_task_org_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_run_tool_calls_run_id"), table_name="run_tool_calls")
    op.drop_table("run_tool_calls")
    op.drop_index(op.f("ix_email_threads_org_id"), table_name="email_threads")
    op.drop_index("ix_email_org_received", table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_index(op.f("ix_consents_org_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_lead_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_claims_org_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_lead_id"), table_name="claims")
    op.drop_index("ix_claim_org_status", table_name="claims")
    op.drop_index("ix_claim_lead_predicate", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_event_org_starts", table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_org_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_suggestions_org_id"), table_name="suggestions")
    op.drop_table("suggestions")
    op.drop_index(op.f("ix_runs_session_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_org_id"), table_name="runs")
    op.drop_index("ix_run_org_created", table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_operators_org_id"), table_name="operators")
    op.drop_table("operators")
    op.drop_index(op.f("ix_leads_org_id"), table_name="leads")
    op.drop_index("ix_lead_org_score", table_name="leads")
    op.drop_table("leads")
    op.drop_table("organisations")
    # ### end Alembic commands ###
